name: Update TOC and Deploy

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:      #  manual triggering

permissions:
  contents: write

jobs:
  update-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run XML and HTML Generation Scripts
        run: |
          python main.py

      - name: Commit and push changes
        run: |
          git config --local user.name 'raffaelemazziotti'
          git config --local user.email "${{ secrets.MY_EMAIL }}"
          git add -f all_journals_toc.xml index.html journals_list.html trends.html trends/
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "Automated weekly update"
          git push
